# Generated by Django 6.0.5 on 2026-05-17 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du produit')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence unique')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('min_threshold', models.IntegerField(default=5, verbose_name="Seuil d'alerte stock bas")),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom du fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du fournisseur')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité transférée')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée (Arrivage/Retour)'), ('OUT', 'Sortie (Vente/Perte)')], max_length=3, verbose_name='Type de mouvement')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notes / Justification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.product', verbose_name='Produit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.supplier', verbose_name='Fournisseur'),
        ),
    ]
